[package]
name = "rust-error-examples"
version = "0.1.0"
authors = ["Nicholas Bishop <nicholasbishop@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
anyhow = "1.0"
command-run = "0.13"
thiserror = "1.0"
